name: audioldm2
repo_id: cvssp/audioldm2-music
pipe:
  num_inference_steps: 500
  audio_length_in_s: 5
  num_waveforms_per_prompt: 1
scheduler:
  num_train_timesteps: 1000
  beta_start: 0.0015
  beta_end: 0.0195
  beta_schedule: scaled_linear
  trained_betas: null
  clip_sample: False
  set_alpha_to_one: False
  steps_offset: 1
  prediction_type: epsilon
  thresholding: False
  dynamic_thresholding_ratio: 0.995
  clip_sample_range: 1.0
  sample_max_value: 1.0
  timestep_spacing: leading
  rescale_betas_zero_snr: False
data:
  name: wav  # wav, mp3
  root: ./data/clips_inst_sample  # [bass, bowed_strings, drums, guitar, percussion, piano, wind]
  sample_rate: 16000
  n_fft: 1024
  hop_length: 160
  win_length: 1024
  n_mels: 64
  power: 2.0
  start_s: 10
  end_s: 15
  start_inpainting_s: 12
  end_inpainting_s: 13