name: diffmusic

defaults:
  - data: moises
  - model: audioldm2  # audioldm2, musicldm
  - inverse_problem: music_inpainting

scheduler:
  eta: 1.0
  ip_guidance_rate: 0.08
  optim_prompt: true
  optim_prompt_learning_rate: 5e-5
