name: dsg

defaults:
  - data: music_data  # moises, music_data
  - model: musicldm  # audioldm2, musicldm
  - inverse_problem: music_inpainting
  - _self_

scheduler:
  eta: 1.0
  ip_guidance_rate: 0.08
  optim_prompt: false
  optim_prompt_learning_rate: 1e-4
  optim_outer_loop: 1
